language: node_js
node_js:
  - "8"
git:
  depth: false
cache: npm
install:
  - npm ci
  - npm run lerna bootstrap
  - npm run build
script:
  - npm run lint
  - npm test
  - npm run test-package
after_script:
  - cd packages/web-compare && ./node_modules/.bin/relative-ci-agent
