version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.5.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "packages/web/package.json" }}
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install && npm run bootstrap

      - save_cache:
          paths:
            - node_modules
            - packages/web/node_modules
          key: v1-dependencies-{{ checksum "packages/web/package.json" }}

      - run:
          name: Test
          command: npm test

      - run:
          name: Build
          command: npm run build


      - store_artifacts:
          path: ./packages/web/artifacts
          destination: artifacts/web

      - run:
          name: Send coveralls for web
          command: cat ./packages/web/artifacts/coverage/lcov.info | node_modules/.bin/coveralls

