# Workflow name
name: chromatic

# Event for the workflow
on: push

jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: npm install && npm run lerna -- bootstrap

      - name: Run chromatic
        run: npm run chromatic --prefix project/ui
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

